# Generated by Django 4.1.3 on 2022-11-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('data', models.IntegerField()),
                ('exp', models.DateField()),
            ],
        ),
    ]
