# Generated by Django 4.1.3 on 2022-11-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='data',
            field=models.BigIntegerField(),
        ),
    ]
